### PR TITLE
[IMDB] fix not play service

### PR DESCRIPTION
**Pull request by Dima73**
File "/usr/lib/enigma2/python/Plugins/Extensions/IMDb/plugin.py", line 655, in getIMDB
AttributeError: 'NoneType' object has no attribute 'toString'

### CODE REVIEW

**Comment by WanWizard** [comment]
Please also apply to the python3 branch.

**Comment by relaxibus** [comment]
I'm using OpenVix 5.3 and the last update here now shows "No Results found" again. It worked with the previous version. Could you fix?

**Comment by Dima73** [comment]
You need to contact https://github.com/OpenPLi/enigma2-plugins/commits?author=scriptmelvin

**Comment by relaxibus** [comment]
Thanks, and how do can I contact him? On his site there is no email.

**Comment by Dima73** [comment]
> Thanks, and how do can I contact him? On his site there is no email.

https://forums.openpli.org/topic/83956-imdb-plugin-issues/

**Pull request merged**
