### PR TITLE
[autoresolution] add option "Smart HDR type (set 'auto' HDMI HDR type)"

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by Marcus051333** [comment]
Thank you for this fix, it works perfectly. There is another problem similar to this, HDMI Colorimetry = auto , also doesn't work. When you change to HDR channel it should switch to BT 2020 Colorimetry but it stays on BT 709. Could you fix this problem in a similar way? I would really appreciate it.

**Comment by Dima73** [comment]
To be honest, I don't see any difference between BT 2020 vs BT 709.
Do you see?

**Comment by Marcus051333** [comment]
> To be honest, I don't see any difference between BT 2020 vs BT 709.
> Is there a difference?

There is. BT 2020 is much wider color gamut than BG 709. The difference is very noticeable on HDR channels.

**Comment by Dima73** [comment]
So...
If HDMI Colorimetry  --> auto
For HDR set BT 2020, other services auto?

**Comment by Marcus051333** [comment]
> So...
> If HDMI Colorimetry --> auto
> For HDR set BT 2020, other services auto?

Yeah exactly

**Comment by Dima73** [comment]
config.av.hdmicolorimetry = ConfigSelection(default="auto", choices=[("auto", _("Auto")), ("bt2020ncl", _("BT 2020 NCL")), ("bt2020cl", _("BT 2020 CL")), ("bt709", _("BT 709"))])

bt2020ncl or bt2020cl?

**Comment by Dima73** [comment]
ok
bt2020ncl

**Comment by Marcus051333** [comment]
Yes both are fine

**Pull request merged**
