### PR TITLE
[dyndns] update to v1.1

### PR DESCRIPTION
**Pull request by nautilus7**
Hi, I have made some changes to the dyndns plugin. Nothing big, altered some text strings, updated skin buttons to new style, and added the necessary structure to support translations.

The plugin code looks too old (released in 2007). I don't really know if it still works correctly with dyndns in 2018. I don't have an account to test, but if worked before, my changes should not brake it.

### CODE REVIEW

**Comment by WanWizard** [comment]
I think most people use inadyn, didn't even know this one exists.

**Comment by nautilus7** [comment]
So, is this useless? Can inadyn be used with dyndns provider? Perhaps, you should you remove the plugin from the repo?

**Comment by WanWizard** [comment]
It looks like it: https://sourceforge.net/projects/inadyn-mt/ 

As far as I can see, this plugin isn't even built anymore. I believe there is a lot of useless old junk in the repo (which is an old copy of schwerkraft before DMM changed the license), it indeed needs someone to go though it, test, and remove if needed.

**Comment by nautilus7** [comment]
I am closing this one... If someone can confirm the plugin still works in year 2018, I can reopen it.

**Pull request closed without merging**
