### PR TITLE
[Blindscan] add new screen Blindscanstate with option to select and d…

### PR DESCRIPTION
**Pull request by Dima73**
…eselect found tp thx betacentauri

- add gigablue arm recievers
- fix io error vuultimo 4k
-do recursive close after scan

### CODE REVIEW

**Comment by athoik** [comment]
Where did search_type moved?

**Comment by Dima73** [comment]
XML file always save:
https://github.com/OpenPLi/enigma2-plugins/blob/3e3b779c15347cd7435aca96c13c07e38c425c76/blindscan/src/plugin.py#L1262
Search stop - press cancel/red key

**Comment by athoik** [comment]
Ok, since we still have xml's it's fine.

Although it would be better to define fec, system, etc only once as globals and reuse then where required.

Currently we redefine them multiple times.

**Comment by Dima73** [comment]
This can be done in the future.
If it will be necessary.

**Comment by WanWizard** [comment]
Is this ok to merge now?

**Comment by Dima73** [comment]
**athoik**?

**Comment by athoik** [comment]
👍 all fine, let's merge it

**Pull request merged**
