### PR TITLE
Fix Blindscan State Screen

### PR DESCRIPTION
**Pull request by BinschePLi**
Fix Blindscan State Screen for FHD Skins (1920x1080)

### CODE REVIEW

**Comment by WanWizard** [comment]
Does this mean the plugin now no longer works on boxes with SD skins?

**Comment by BinschePLi** [comment]
for example, pls show the pics in forum: https://forums.openpli.org/topic/72556-openpli-blindscan-plugin-fullhd-skin-fixmod/
is there another possibility to "zoom" or "stretch" the (current) state window at using a fhd skin?

**Comment by WanWizard** [comment]
@littlesat can you point out how a plugin can best support both SD and HD skins?

**Comment by BinschePLi** [comment]
i see, there is a bigger conflict between using fhd-skins and hd-skins, because the state screen is at the moment defined with fix sizes into the plugin.
either it is correctly for hd-resolution skins (1280x720) like the "original" plugin.py or for fhd-resolution skins (1920x1080), with my changes.
the simplest solution, not the nicest: 2 different blindscan plugins :D (one for these skin resolution, another for the other skin resolution)

**Comment by BinschePLi** [comment]
another solution, and my favorite: i define the screen "BlindscanState" not more longer at the plugin itself, rather in the skin.xml from the skin (<screen name="BlindscanState" </screen>). so my changes in the skin.xml has priority over the screen in the plugin.py. works -> great, and is update-safe

**Comment by littlesat** [comment]
It is always better to put the screen in the skin_plugins.xml.... skin in python code is only for fallback when you installed skin that does not support the plugin. Therefor it is also smart to use screens that are already available in most skins... eg for a config use the setup screen and only add a screen when it is really needed!!!

**Comment by BinschePLi** [comment]
Thx. i will take a closer look at the procedure later. i dont know the attribute <panel>

**Comment by Dima73** [comment]
sz_w = getDesktop(0).size().width()
	# FHD
	if sz_w >= 1920:

**Comment by littlesat** [comment]
Please not another desktop size check.... when you really want to do that than put it in SystemInfo or so, so you can ask it once...

**Comment by BinschePLi** [comment]
> Thx. i will take a closer look at the procedure later. i dont know the attribute

I did not know the attribute <panel name = "BasicTemplate" /> in the plugins_skin.xml file and the dependencies of it with <screen name="BasicTemplate"> . Now everything is good. I understood how I work with it. In my view, the request can be deleted/closed. Thanks @ all

**Comment by nautilus7** [comment]
@BinschePLi the skin embedded in the plugin code is just a safety precaution, in case the plugin is not supported by the **current skin** you are using and should never be used in practice. As such, it should have the same resolution as the "skin default" in openpli, that is SD. That being said the original resolution of "820,570" is also wrong, as it wouldn't fit the SD resolution.

If you want a bigger screen, make sure the skin you use supports the plugin properly.

**Comment by nautilus7** [comment]
@littlesat the "setup" screen cannot be used here, because the configuration screen of the plugin has some extra elements (for displaying the rotor position). But I generally agree with re-using as much of the existing screens, and not introducing new ones.

In addition, I have seen plugins using 10-15 different screens, which are a pain in the ass to support in a new skin. What are their auhtors thinking?

**Comment by BinschePLi** [comment]
> If you want a bigger screen, make sure the skin you use supports the plugin properly.

Yes, i understood that by now and i have done that for a long time (a few days) ;-) My own used skin is now perfectly skinned for the blindscan plugin (state screen): https://postimg.cc/gallery/3fcr2jk1s/

How can i delete this request? Or can anyone delete it pls? Or does it no matter?

**Comment by nautilus7** [comment]
Nice!

You just "close" the request. It cannot be deleted.

**Comment by BinschePLi** [comment]
ok. thx for your help, so i close now

**Pull request closed without merging**
