### PR TITLE
[autotimer] hidden option encoding

### PR DESCRIPTION
**Pull request by Dima73**
-this need for python3
File
"/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py", line 322, in parseTimer

builtins.AttributeError: 'str' object has no attribute 'decode'

### CODE REVIEW

**Review by littlesat — COMMENTED** [review]
Just remove them and do not comment them out when they are not needed anymore

**Comment by WanWizard** [comment]
The issue I have with this, is that it doesn't fix the root cause of the problem, the encoding issue. Instead a a bytesarray with non-UTF8, in Python3 you'll have a string object with non-UTF-8.

So imho the setting and the fix is still needed, the code needs to be made Python3 compliant (which is not easy if you don't know the source encoding).

**Comment by Dima73** [comment]
> The issue I have with this, is that it doesn't fix the root cause of the problem, the encoding issue. Instead a a bytesarray with non-UTF8, in Python3 you'll have a string object with non-UTF-8.
> 
> So imho the setting and the fix is still needed, the code needs to be made Python3 compliant (which is not easy if you don't know the source encoding).

In other images this has long been removed.

**Comment by WanWizard** [comment]
And that proves it is ok?

**Pull request merged**
