### PR TITLE
[Autotimer] update for new options

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by eriksl** [comment]
This really has to be split up.

How about this???

+try:
-typeMap = {
+	typeMap = {
-	"exact": eEPGCache.EXAKT_TITLE_SEARCH,
+		"exact": eEPGCache.EXAKT_TITLE_SEARCH,
-	"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
+		"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
-	"start": eEPGCache.START_TITLE_SEARCH,
+		"start": eEPGCache.START_TITLE_SEARCH,
-	"description": -99
+		"description": -99
-}
+	}
+except:
+	typeMap = {
+		"exact": eEPGCache.EXAKT_TITLE_SEARCH,
+		"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
+		"start": eEPGCache.PARTIAL_TITLE_SEARCH,
+		"description": -99
+	}

**Comment by Dima73** [comment]
This plugin need works for all images:
if image not eEPGCache.START_TITLE_SEARCH
eEPGCache.START_TITLE_SEARCH = eEPGCache.PARTIAL_TITLE_SEARCH

It is not who does not interfere...

**Comment by eriksl** [comment]
Only one of the four entries is different. I'm sure you can come up with something that only handles the different one and then handle the other three with one set of code.

Anyway, I still think the patch is far too large.

**Comment by Dima73** [comment]
Please apply the patch.
This is my last big change plugin.

**Comment by littlesat** [comment]
Why does this verschoen on our git need to work on multiple images as it requires an ugly patch???

**Comment by Dima73** [comment]
fixed

**Comment by eriksl** [comment]
Fix accepted.

It's still a very large patch though. I will apply it tentatively. With that I mean that if complaints arise, you fix it quickly or I will revert the complete patch.

**Pull request closed without merging**
