### PR TITLE
Fixed italian translation VfdControl plugin

### PR DESCRIPTION
**Pull request by Gringit**
vy Gringo

### CODE REVIEW

**Comment by WanWizard** [comment]
it can't be merged, due to conflicts in "networkbrowser/po/it.po" and "vfdcontrol/po/it.po". 

Please update your local clone from upstream, fix the merge issue, and create a new PR.

**Comment by WanWizard** [comment]
p.s. these translations have the same problem as your previous ones. Please do not include a trailing newline (\n) in the translation when the original doesn't have one. It will break the build.

**Comment by Gringit** [comment]
Ok, i put the (\n) to allow a carrier return to instead to use a unique row which in italian is terrible.
Anyway, I'm gonna fix the .po file to solve the problem.

Regards

**Comment by WanWizard** [comment]
You can only do that when the \n is also present in original text, in the source.

**Pull request closed without merging**
