### PR TITLE
[blindscan] remove wrong code

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by Dima73** [comment]
> What was wrong here? We can we not convert it to int for example why should it be string and then compare with integer ?

This error occurred when switching to python3
same as oe-alliance
[[Blindscan] Fix a bug introduced here:](https://github.com/oe-alliance/oe-alliance-plugins/commit/269feb5a4a340bf5a8f4195e41ee1229bb474058) https://github.com/oe-alliance/oe-alliance-plugins/commit/94e34bb3588203bba63a11c0ff39364831d944dc

**Comment by littlesat** [comment]
As far I can see the fix is not good. You split it in a string and than later you compare with integer. This should lead to other complications with py3 as far I can see.

**Comment by littlesat** [comment]
I do not merge when it does not feel good and this does not feel good. So why do we have a problem with vu and not the others here and why do we not got the issues with parsing this file elsewhere?

**Comment by Dima73** [comment]
This worked for many years.
Someone added an int for python3.
So ask him why he did it.

**Comment by WanWizard** [comment]
Closing it doesn't fix it, and neither does "a bad feeling". 

So are we going to leave it broken now?

**Comment by littlesat** [comment]
I prefer to do it really good... comparing integer with string is what we should try to avoid... especially when also >= 0 is involved...

**Comment by littlesat** [comment]
There is a check > 0 that is not good. And I think we should simply try to avoid it. Think about python 'closes' then door even more....

**Comment by Dima73** [comment]
There is an original version of the plugin from o-e and there is an author.
And I need as much compatibility with the original as possible, this is important when comparing the code for some problems.
Therefore, I try not to change anything superfluous, although I understand that the code in this place is not entirely perfect.
I've been doing this plugin for many years, do you want me to drop it?
Who will benefit from this?
After all, you will not change it when it is necessary, right?
The same as with slot 0 (multboot wu +).
Just words, words, words...

I'm not a few years old and it's a pity to waste time.

**Comment by littlesat** [comment]
I would keep it integer and instead of -1 use None.... Most likely when you add a line = line.strip() the transfer to int should work.

**Comment by Dima73** [comment]
For what?
What is the difference?
Okay, enough, let's leave it as it is.

**Comment by littlesat** [comment]
Why give up?
Just try to add the line with the strip()... instead of 'hacking' around.

**Comment by littlesat** [comment]
Was it on a vu+ where this was going wrong ?

**Comment by littlesat** [comment]
Can you please post the a crashlog where it does go wrong so I can take a look into this one so I can try and help to make this good.

**Comment by littlesat** [comment]
Can you please post the a crashlog where it does go wrong so I can take a look into this one so I can try and help to make this good.

**Comment by littlesat** [comment]
Can you please post the a crashlog where it does go wrong so I can take a look into this one so I can try and help to make this good.

**Pull request closed without merging**
