### PR TITLE
Weather plugin fixes for python3 -- still not working, similar to python2

### PR DESCRIPTION
**Pull request by nautilus7**

### CODE REVIEW

**Comment by Hains** [comment]
Yes it's deprecated. 
Disconnected int 2019.

Two options:
-Switch to e.g. Virtual crossing
https://www.visualcrossing.com/resources/documentation/weather-data/getting-started-with-weather-data-services/

I have account and key.
I can send it to you by PM if you want?
Data in json, so we need to convert data to Excel.

Option two:
-Drop the plugin. 
  We have Foreca plugin as replacement.

**Comment by nautilus7** [comment]
My opinion is to drop the plugin completely. Like you said, there are other plugins for weather. Better have a single one that gets all our attention and focus and has a nice ui (unlike this one).

btw, the [oe-alliance version](https://github.com/oe-alliance/enigma2-plugins/blob/master/weatherplugin/src/MSNWeather.py#L132) is using msn weather...

@WanWizard @athoik what's your opinion? should we remove completely old and deprecated plugins like this one?

**Comment by WanWizard** [comment]
I use neither this one, nor Foreca. I use the HetWeer plugin (which has international support although the name doesn't suggest it).

I'd say dump it.

**Comment by athoik** [comment]
I say R.I.Py2

**Pull request merged**
