### PR TITLE
Blindscan: add MIS/PLS info in BlindscanState screen

### PR DESCRIPTION
**Pull request by athoik**

### CODE REVIEW

**Comment by athoik** [comment]
@Dima73 maybe we need to add selection in front? 

1_0_1_a_2_212c_eeee0000_0_0_0_20181021125444

Here how it looks without MHz and SR.

1_0_1_a_2_212c_eeee0000_0_0_0_20181021125814

Also some people don't like the "two step" blindscan. 

Maybe we can bring back "scan channels" or "save to xml"? 

The "scan channels" will not prompt user to select just like we used to do. The "save to xml" will display the new screen that allows user to select.

**Comment by Dima73** [comment]
I'm not against.
But the choice of channels for scanning was not very bad.

**Comment by athoik** [comment]
Indeed, was not very bad, but some people already don't like the "two step" process.

So the default will be again the "scan for channels".

1_0_1_1b00_3fe_1_c00000_0_0_0_20181021133101

Then scan for transponders, will bring the new Blindscan screen.

1_0_1_1b00_3fe_1_c00000_0_0_0_20181021133125

**Comment by athoik** [comment]
@Dima73, what about the MHz and SR. Remove them too?

**Comment by Dima73** [comment]
Yes, it looks much better.
`what about the MHz and SR. Remove them too?`
Yes,remove.And so it will be clear.

**Comment by athoik** [comment]
OK done!

I think we can merge it now! 

Maybe we can finetune the output in order MIS/PLS (and soon T2MI) to fit, in the future.

**Pull request merged**
