### PR TITLE
[autoresolution] suppport GB "gbue4k"/ "gbquad4k"

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
If box x then do y should be avoided. Can't we make a feature of it?

**Comment by Dima73** [comment]
The problem is completely different(only Gigablue "gbue4k"/ "gbquad4k"), /proc/stb/video/videomode exists, writing to /proc/stb/video/videomode does not work.
When write /proc/stb/video/videomode_50hz /proc/stb/video/videomode automatically changes same as /proc/stb/video/videomode_50hz .
I don't see any other way.

**Comment by littlesat** [comment]
So you're trying to solve a bug in the gigablue drivers? Maybe write to it and when there is no response by reading the value back write in 50Hz proc with a comment when it is not written write it in another proc due to a gigablue bug

**Comment by Dima73** [comment]
Well, why is it so difficult?
And it won't work 100% percent.
A simple model validation solves all problems.

**Comment by littlesat** [comment]
Because putting if box x then do y is note done... the only exception is SystemInfo.py. Maybe add a SystemInfo key for the proc and put the correct proc in SystemInfo.py and call instead of the complete path this SystemInfo key. Sometimes 'rules' intended for structured way of programming is a pain but they are helpful. It is good that all exceptions are just in one file. Sometimes too simple is not good

**Comment by Dima73** [comment]
I understand everything, but...
I don't want to tie the SystemInfo.py from the openPli image to this plugin at all, because the plugin can be used on other images as well.

**Comment by littlesat** [comment]
For openpli this is not the way. As far I know other images also have SystemInfo. So that should not be the issue. I think it is mandatory to avoid if box x then do y. Is shouldn't be in either and already SystemInfo is the compromis we made years ago.

**Comment by Dima73** [comment]
Compromise?

**Comment by littlesat** [comment]
Tell, only when we do not have if box x then do y...

**Comment by littlesat** [comment]
Still not good... if box x then do y is only allowed in SystemInfo.py. Sorry that I have to be hard here. Just move it there as far I know all other images have SystemInfo.py so it should not be that hard.

**Comment by Dima73** [comment]
But I will have to add an additional check that such a parameter exists in SystemInfo.py.
And if it does not exist, different versions of Enigma2, then you will have to use this code.
proc_videomode = HardwareInfo().get_device_model() in ("gbue4k", "gbquad4k") and "/proc/stb/video/videomode_50hz" or "/proc/stb/video/videomode"
But it's stupid...

**Comment by littlesat** [comment]
Please no! Please let the other images add it as well or let them modify it... sorry

**Comment by littlesat** [comment]
Do other images use our plugins from GitHub?

**Comment by Dima73** [comment]
Don't know.
But the plugin can be installed manually on another image and it will work.
If  add SystemInfo then compatibility will be lost.

**Comment by littlesat** [comment]
So be it...

**Comment by littlesat** [comment]
It box x then do y should still be out of it.... other images can also add SystemInfo key.

**Comment by Dima73** [comment]
> It box x then do y should still be out of it.... other images can also add SystemInfo key.

I don't understand.
What should the code look like?

**Comment by littlesat** [comment]
The or hardware info should be out...
Actually this is fully not done....
Much much more better gigablue fixes their driver but!!!!! As that is the root cause....
But can't you read the proc back after you write it and when it is not written try the _50Hz or does the gigablue driver accept when you write to it without a result?

**Comment by Dima73** [comment]
` does the gigablue driver accept when you write to it without a result?`
Yes, that is right.
Therefore, it is not possible to tell the difference between other models.
That's why I'm directly assigning the processor string through the model.
As for drivers...
You know that no one supports them anymore.

**Comment by littlesat** [comment]
And nobody can contact gigablue to fix the bug? So nothing is needed here?

**Pull request merged**
