### PR TITLE
Transcoding: port is set as a static port 8001 or 8002

### PR DESCRIPTION
**Pull request by zgemma-star**
Transcoding: add extra videoresolution for newer chipsets

### CODE REVIEW

**Comment by eriksl** [comment]
Comment 1: the port selection code is useless on OpenPLi because on port 8002 the streamproxy will be listening, enigma can't use it.

**Comment by eriksl** [comment]
Comment 2: why change the default transcoding resolution?

**Comment by eriksl** [comment]
Also I don't understand the fiddling with the existing resolutions. I am assuming the resolution specifies raw resolution without aspect ratio applied, as is usual in a video stream. I think the Broadcom interface works that way anyway. So I am hesitant to apply it globally this way.

**Comment by eriksl** [comment]
The second commit is a single line with all of the rest of it in commit #1...

**Comment by zgemma-star** [comment]
Comment1 is just for port info. Many people are confused which port to set. Now you see in the settings if it's the standard port for streams or port 8002.

Comment2 The extra resolution are possible with the newer chipset like hisilicon. Like broadcom doesn't support 1080p.
To have 16:9 or 4:3 or other aspect ratio we can only do it by set the resolution width and height.
The option to add aspect ratio flag in the header seems not available on hisilicon platform and it's value is ignored.

**Comment by zgemma-star** [comment]
https://github.com/OpenPLi/enigma2-plugins/pull/568
Adjust only settings for new boxes with h265 encoder.

**Pull request closed without merging**
