### PR TITLE
presettings for openwebif

### PR DESCRIPTION
**Pull request by zgemma-star**
add vcodec option

### CODE REVIEW

**Comment by eriksl** [comment]
The purpose of this plugin is not to set up transcoding, it's only purpose is to satisfy OpenWebInterface requirements for transcoding. The changes in this commit do a lot more than "add vcodec option".

The proper way to go is to extend the transcoding/streaming interface of enigma with a video codec parameter.

**Comment by zgemma-star** [comment]
OpenwebIF collect the settings from enigma2-plugin-systemplugins-transcodingsetup
The plugin doesn't provide direct the information. Your force to save the settings first before it works.
The plugin fix the problem for some models and add the vcodec when Openwebif request it.

**Comment by WanWizard** [comment]
The root cause is the dependency of OpenWebIf to this plugin, while on OpenPLi this dependency does not exist. So the issue needs to be adressed in OpenWebIf.

**Comment by zgemma-star** [comment]
With the latest adjustment Openwebif gets the right values for bitrate and resolution.
The bug is fixed and vcodec option is add. The topic can been closed (again).

**Comment by pieterg** [comment]
see https://github.com/OpenPLi/enigma2-plugins/pull/361

Thanks for confirming things are OK now.

**Pull request closed without merging**
