### PR TITLE
Fix slowness and missing user review

### PR DESCRIPTION
**Pull request by scriptmelvin**
- Fix slowness and missing user review
- Merge python2 and python3 versions
- Change back from urllib(2) to twisted web

### CODE REVIEW

**Comment by WanWizard** [comment]
What do you mean by "Merge python2 and python3 versions"? 

Python3 is built from the python3 branch, so that still needs updating too.

**Comment by scriptmelvin** [comment]
> What do you mean by "Merge python2 and python3 versions"?

There were two versions of the plugin, the old one (python2)  and the one turned into python3 by @Hains. I combined them into one version that runs on both python2 and python3.

> Python3 is built from the python3 branch, so that still needs updating too.

Yes I know :-)

**Comment by WanWizard** [comment]
Unfortunately we can't build from a different branch per plugin.

I'm planning on moving the py3 versions of plugins that are still relevant to e2openplugins, with a repo per plugin, which will make maintenance and building a lot easier.

**Comment by scriptmelvin** [comment]
> Unfortunately we can't build from a different branch per plugin.

I understand. But it seemed logical (to me) to have only one plugin.py and have two (identical) copies of it in two branches, instead of two different plugin.py, one in each branch.

> I'm planning on moving the py3 versions of plugins that are still relevant to e2openplugins, with a repo per plugin, which will make maintenance and building a lot easier.

Great idea.

**Pull request merged**
