### PR TITLE
Autotimer list - fixed icons, optimalized full HD extended list

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by littlesat** [comment]
If hd... brrr... every plugin that needs to recheck this... when you want this better centralize it and just include eg an OSDisHD variabele...

**Comment by ims21** [comment]
It was used there before. Close it. I am ending with it !

**Comment by littlesat** [comment]
Why close it... when merged it should be good!

**Comment by littlesat** [comment]
Why close it... when merged it should be good!
Please also note I also adapted the comments... the HD solution by getting the osd size is somehow not done.

**Comment by ims21** [comment]
Changed without HD value ... pars added into skin.py and into skin.xml

**Pull request closed without merging**
