### PR TITLE
blindscan: Add support for Ka-Band

### PR DESCRIPTION
**Pull request by athoik**
This commit merges all the latest development from @Huevos made on OE-A plugin.

[Blindscan] Add Ka Band
This adds 4 popular non-inverted LNBs as follows:

Ka ( A ) 18.2-19.2 LOF 17250
Ka ( B ) 19.2-20.2 LOF 18250
Ka ( C ) 20.2-21.2 LOF 19250
Ka ( D ) 21.2-22.2 LOF 20250

[Blindscan] Subtitute Ka with "user defined" local oscillator frequencies
Also start a clean up. Replace hard coded numbers with variables with name that make the code easier to understand.

[Blindscan] If the LNB configured for the current satellite is not compatible with the plugin, disable the green button and show an error message

[Blindscan] Remove circular LNB scan
Circular LNB scan is now handled as a user defined scan and follows that code path.

[Blindscan] Make duplicate detection more agressive and optional.

### CODE REVIEW

**Comment by athoik** [comment]
@Dima73 please check if circular still works (now it's handed by user defined LNB code).

**Comment by Huevos** [comment]
Works for me. Based on local oscillator of 10750 it shows band limits of 11700 - 12900. That covers the real band plus a little bit more.

**Comment by Huevos** [comment]
DIma can you show me with a patch. I am not following your suggestion.

**Comment by Dima73** [comment]
Please
[patch.zip](https://github.com/OpenPLi/enigma2-plugins/files/2593065/patch.zip)

**Comment by Huevos** [comment]
Hi, Why don't we want to break?

-					break
+					#break

**Comment by Dima73** [comment]
This is superfluous, I cleaned up.

**Comment by Huevos** [comment]
But why should we run the loop to the end even though we already have a result?

**Comment by Dima73** [comment]
All right, I do not clean up 'break'.

**Comment by Huevos** [comment]
```
 			elif lof == "user_defined" and currLnb.lofl.value == currLnb.lofh.value and currLnb.lofl.value > 5000 and currLnb.lofl.value < 30000:
-				self.user_defined_lnb_lo_freq = currLnb.lofl.value
+				if currLnb.lofl.value == 10750 and currLnb.lofh.value == 10750 and cur_orb_pos in (360, 560):
+					self.user_defined_lnb_lo_freq = self.circular_lnb_lo_freq
+					self.suggestedPolarisation = _("circular left/right")
+				else:
+					self.user_defined_lnb_lo_freq = currLnb.lofl.value
 				self.user_defined_lnb_scan = True
 				print "[Blindscan][SatBandCheck] user defined local oscillator frequency: %d" % self.user_defined_lnb_lo_freq
 				return True
```

Why do we need that? There is code for "circular_lnb" here...

`elif lof == "circular_lnb": # lnb for use at positions 360 and 560`

**Comment by Dima73** [comment]
Because many users use this outdated configuration option.
I don’t understand what the problem is, if I just tell them what it is "circular left/right".

**Comment by Huevos** [comment]
Dima73, it is not a problem, I just wanted to know the logic. 

Anyway, you have added a PR so hopefully nothing more to do.

**Pull request merged**
