### PR TITLE
all necessary parameter for streamproxy available

### PR DESCRIPTION
**Pull request by anudanan**
als parameter and the new language parameter for streamproxy.conf are setable by transcodingsetup and OWIF transcoding settings

### CODE REVIEW

**Comment by WanWizard** [comment]
@eriksl ?

**Comment by littlesat** [comment]
Erik?

**Comment by anudanan** [comment]
No interesting for that? From my point of view it works better than before for normal users

**Comment by ims21** [comment]
I think, you must ping Erik on forum, but not with PM.

**Comment by littlesat** [comment]
Why fixed bitrates from a table... it reduces flexebility... is this still actual?

**Comment by anudanan** [comment]
> Why fixed bitrates from a table... it reduces flexebility... is this still actual?
This  table was also in the older version, I´ve one added some more bitrate values and I think it is easier to use a choicetable for a user than typing in the complete value if the user will change the rate. if you thing the steps are to far we can added more bitrate choices

**Comment by anudanan** [comment]
> Why f open read the f close as you can all do it in a oneliner?

what do you mean?

**Comment by littlesat** [comment]
Don’t worry... Erik is somehow streamproxy specialist he should evaluate this... but I mean you could make the parsing of the conf file and writing of it more easily...

**Comment by eriksl** [comment]
I am veeeeeery bad at Python. If some of you think the plugin can be improved, please be my guest. I will never need it myself, as it the transcoding system of OpenPLi really doesn't need a "setup", it's only for the OpenWebIF.

**Comment by littlesat** [comment]
Is there still a need for this one.... the python part has also Some ‘tricky’ thingszzz

**Comment by anudanan** [comment]
from my point of view it is very usefull to setup all streamproxy settings over the enigma GUI and with openwebif. Also the IOS app enigmote use the openwebif to set the transcoding settings and with these changes it works very well.
I use it until now on my two openpli uno4kse boxes

**Comment by ims21** [comment]
I think, option for setting language track (or use existing "set language priority" setting from e2 for it) for any transcoding would be very useful. Now is used first audio track always and it is not good.

**Comment by littlesat** [comment]
In between it conflicts :(

**Pull request closed without merging**
