### PR TITLE
[blindscan] update FBC not support tuner list

### PR DESCRIPTION
**Pull request by Dima73**
-protect against unexpected values in satellites.xml
 -add some defaults, this is to avoid crashes if the binary returns junk

thanks @Huevos

### CODE REVIEW

**Comment by Dima73** [comment]
> Again if box x then y all over the plugin. Can't we find a different solution for it?

I ran into the problem of defining a model many years ago and therefore I check it directly.
Ang there are no errors.
And it has been working for many years.

**Comment by Huevos** [comment]
They are tuners, not boxes. How else would you suggest we list tuners that are not compatible?

**Comment by Huevos** [comment]
> And I also thing the blindscan plugin is even not a very helpfull plugin as for real blindscan it would be much much better to have a spectrum analyzer like thing....
> 

Which manufacturers supply a spectrum analyser binary. And anyway I doubt any of these enigma2 tuners are capable, after all it is a hardware feature (just like blindscan).

**Comment by littlesat** [comment]
Maybe the hardware can do. At least I know for some tuners when the drivers do support it. And then we have another pain for this feature we need different binaries. There is no real api like thing.

**Comment by littlesat** [comment]
There is a way for a lot of tuners that it can be done...

**Pull request merged**
