### PR TITLE
[blindscan] fix crash when vublindscan send unsupport fec options

### PR DESCRIPTION
**Pull request by Dima73**
thanks @atvcaptain

### CODE REVIEW

**Comment by athoik** [comment]
Why don't you add a single line? 

`parm.fec = fec.get(data[7], eDVBFrontendParametersSatellite.FEC_Auto)`

**Comment by athoik** [comment]
Why don't you add a single line? 

`parm.fec = fec.get(data[7], eDVBFrontendParametersSatellite.FEC_Auto)`

**Comment by athoik** [comment]
You can remove all FEC now, the single line is enough.

**Comment by Dima73** [comment]
Are you sure?
Maybe they should be left for information?

**Comment by athoik** [comment]
Once there are available in Linux kernel, sure let's add available FEC's.

Currently it's just extra code offering nothing more than the single line check.

**Comment by Dima73** [comment]
I suggest you create a separate patch.

**Pull request closed without merging**
