### PR TITLE
[autoresolution]  replace fps 30 --> 60 always if support '1080'

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by eriksl** [comment]
This seems to assume that every receiver that support 1080 does support 60 Hz progressive? Invalid for a.o. dm800se, dm8000, xtrend 9x00 series, duo, etc. I am not sure if you'd want to "upscale" 29.97 Hz (deinterlaced) to 60 Hz (interlaced) on those models.

**Comment by Dima73** [comment]
No, now 30Hz will always as 60Hz.

**Comment by eriksl** [comment]
30 Hz progressive to 60 Hz interlaced will not always be a quality improvement.

**Comment by Dima73** [comment]
https://github.com/OpenPLi/enigma2-plugins/pull/240

**Pull request merged**
