### PR TITLE
Create bg.po

### PR DESCRIPTION
**Pull request by marto74bg**
Bulgarian translation for Network Browser.

### CODE REVIEW

**Comment by pr2git** [comment]
Hi,
When you add a new translation file please don't forget to also edit the associated: Makefile.am and add the language in the LANGS parameter. So in this case you need to add bg in the list. Otherwise your translation will not be included in the plugin package and your work will not be visible.
Pr2

**Comment by pr2git** [comment]
Please don't do anything I have added bg in the Makefile.am in my last PR.

**Comment by WanWizard** [comment]
So this can be merged?

**Comment by pr2git** [comment]
Yes please merge it, I have modified the Makefile.am in the PR that you already approuved.

**Comment by ims21** [comment]
Pls, merge it ... It is not possible build due missing bg.po in repo.

**Pull request merged**
